name: SSL Check

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '0 16 * * *' 

jobs:
  CheckSSL:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install & Build
      run: |
        TZ='Asia/Shanghai'; export TZ
        npm i
        git clone https://github.com/Guangsudalao/CheckSSL --depth=2
        npm run build
        cd CheckSSL
        chmod +x checker.sh
        ./checker.sh dlya.top www.dlya.top blog.dlya.top ssl.dlya.top cdn.dlya.top static.dlya.top file.dlya.top avatar.dlya.top pan.dlya.top playing.dlya.top waline.dlya.top 
        cp -rf ./output/ct.json ../public/ct.json
        echo "ssl.dlya.top" > ../public/CNAME
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./public
